name: C/C++ CI

on:
  push:
    branches: [ master, develop, fix ]
  pull_request:
    branches: [ master, develop, fix ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make TARGET_ARCH=x8664
    - name: make test
      run: make test TARGET_ARCH=x8664
 
